# Generated by Django 4.0.2 on 2022-06-08 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_rename_name_de_attribute_name_uz_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='values',
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='attribute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.attribute'),
        ),
    ]
