# Generated by Django 4.0.2 on 2022-06-14 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_attribute_name_en_attributevalue_value_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='variants',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
