# Generated by Django 4.0.2 on 2022-06-25 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_productfavorite_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariant',
            old_name='price',
            new_name='price_for_beautician',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='price_for_entity',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=21),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productvariant',
            name='price_for_private',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=21),
            preserve_default=False,
        ),
    ]
