# Generated by Django 4.0.2 on 2022-06-27 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_productreview'),
        ('product', '0011_rename_price_productvariant_price_for_beautician_and_more'),
    ]

    operations = [
    ]
