# Generated by Django 4.0.2 on 2022-07-26 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_discount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
