# Generated by Django 4.0.2 on 2022-07-14 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_phone_number_verifyuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='speciality',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
