# Generated by Django 4.0.2 on 2022-09-12 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_address_building_floor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='region',
        ),
        migrations.RemoveField(
            model_name='address',
            name='shipping_region',
        ),
    ]
