# Generated by Django 4.0.2 on 2022-08-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertransaction',
            name='payment_type',
            field=models.CharField(choices=[('paypal', 'paypal'), ('stripe', 'stripe')], default='stripe', max_length=20),
        ),
        migrations.AddField(
            model_name='ordertransaction',
            name='paypal_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ordertransaction',
            name='status',
            field=models.CharField(choices=[('processing', 'processing'), ('success', 'success'), ('canceled', 'canceled')], default='processing', max_length=20),
        ),
        migrations.AlterField(
            model_name='ordertransaction',
            name='stripe_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
