"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""
import sys, os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
sys.path.append(os.path.join(BASE_DIR, 'apps'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'mptt',
    'django_filters',
    'modeltranslation',
    'easy_thumbnails',
    'corsheaders',
    'django_crontab',

    # Apps
    'user',
    'file',
    'product',
    'order',
    'blog',
    'company_info',
    'banners',
    'payment',
    'transaction'
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOW_ALL_ORIGINS = True
ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'
AUTH_USER_MODEL = 'user.User'

# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DATABASE_NAME', 'oncosmetic'),
        'USER': os.environ.get('DATABASE_USER', 'oncosmetic_user'),
        'PASSWORD': os.environ.get('DATABASE_PASSWORD', 'oncosmetic_password'),
        'HOST': os.environ.get('DATABASE_HOST', '127.0.0.1'),
        'PORT': os.environ.get('DATABASE_PORT', '5432'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-Us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

MODELTRANSLATION_LANGUAGES = ('de', 'ru', 'en')
MODELTRANSLATION_DEFAULT_LANGUAGE = 'en'
MODELTRANSLATION_TRANSLATION_FILES = [
    'product.translation',
    'blog.translation',
    'company_info.translation',
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/
PROJECT_DOMAIN = os.environ.get('DOMAIN', 'apicosmetic.novalabtech.com')
FRONT_DOMAIN = os.environ.get('FRONT_DOMAIN', 'https://on-cosmetics.vercel.app/')

STATIC_URL = '/static/'
STATIC_ROOT = os.environ.get('STATIC_URL', os.path.join(BASE_DIR, 'static'))

MEDIA_URL = '/media/'
MEDIA_ROOT = os.environ.get('MEDIA_URL', os.path.join(BASE_DIR, 'media'))

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Rest framework settings
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.OrderingFilter',
        'rest_framework.filters.SearchFilter',
    ],
    'DEFAULT_PAGINATION_CLASS': 'core.pagination.PageNumberPagination',
    'PAGE_SIZE': 25
}

# SENDGRID Mail
SENDGRID_API_KEY = os.environ.get(
    'SENDGRID_API_KEY', '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'
)
SEND_GRID_FROM_EMAIL = os.environ.get('SEND_GRID_FROM_EMAIL', 'info@novalabtech.com')

# Stripe
STRIPE_KEY = 'pk_test_K6B5l6lkrruXmrZQc7MnV95w001nfeqK6g'
STRIPE_SECRET_KEY = 'sk_test_c1REDYL0szRN3NC52nYuSLPS00yWmdFKSo'

PAYPAL_CLIENT_ID = 'AYcKiSmflG-mBICTArHsT8FmRODRemtKLNZcMRBrP64KFwG2XCtLZhtdAkB4TF4xD6-40uiKn9HhhD7K'
PAYPAL_SECRET_KEY = 'EOzqlIpx4_c2j8o41CXEC-UadNOrrxHea_U4oArNZn1qLAvCYjQTpP1itLN-B1N1jAZRunhmk8soDqhx'

CRONJOBS = [
    ('0 0 * * *', 'product.services.discount.change_discount_status'),
]
