# Generated by Django 4.0.2 on 2022-07-06 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('stripe', 'stripe'), ('paypal', 'paypal')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='total_discount',
            field=models.DecimalField(decimal_places=2, max_digits=21, null=True),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='discount_price',
            field=models.DecimalField(decimal_places=2, max_digits=21, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('processing', 'processing'), ('finished', 'finished'), ('canceled', 'canceled')], default='new', max_length=20),
        ),
    ]
