# Generated by Django 4.0.2 on 2022-07-14 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('processing', 'processing'), ('packaging', 'packaging'), ('deliver', 'deliver'), ('finished', 'finished'), ('canceled', 'canceled')], default='new', max_length=20),
        ),
    ]
