# Generated by Django 4.0.2 on 2022-07-14 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('paid', 'paid'), ('packaging', 'packaging'), ('deliver', 'deliver'), ('delivered', 'delivered'), ('canceled', 'canceled')], default='new', max_length=20),
        ),
    ]
