# Generated by Django 4.0.2 on 2022-07-20 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price_to_paid',
            field=models.DecimalField(decimal_places=2, max_digits=21, null=True),
        ),
    ]
