# Generated by Django 4.0.2 on 2022-08-01 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_orderproduct_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('stripe', 'stripe'), ('paypal', 'paypal')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('paid', 'paid'), ('packaging', 'packaging'), ('deliver', 'deliver'), ('delivered', 'delivered'), ('canceled', 'canceled')], default='new', max_length=9),
        ),
    ]
