# Generated by Django 4.0.2 on 2022-09-08 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_order_payment_type_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dhl_tracking',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
    ]
