# Generated by Django 4.0.2 on 2022-10-10 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_order_dhl_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price_to_paid_with_tax',
            field=models.DecimalField(decimal_places=2, max_digits=21, null=True),
        ),
    ]
