# Generated by Django 4.0.2 on 2022-06-21 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=56, verbose_name='banner title')),
                ('description', models.CharField(max_length=100, verbose_name='banner description')),
                ('is_active', models.BooleanField(default=False)),
                ('language', models.CharField(choices=[('en', 'en'), ('ru', 'ru'), ('de', 'de')], default='en', max_length=25)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file.file', verbose_name='banner image')),
            ],
            options={
                'verbose_name_plural': 'Banners',
            },
        ),
    ]
