# Generated by Django 4.0.2 on 2022-08-01 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
        ('banners', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={},
        ),
        migrations.AddField(
            model_name='banner',
            name='description_de',
            field=models.CharField(max_length=155, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='description_en',
            field=models.CharField(max_length=155, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='description_ru',
            field=models.CharField(max_length=155, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='title_de',
            field=models.CharField(max_length=63, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='title_en',
            field=models.CharField(max_length=63, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='title_ru',
            field=models.CharField(max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='description',
            field=models.CharField(max_length=155),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='file.file'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='language',
            field=models.CharField(choices=[('en', 'en'), ('ru', 'ru'), ('de', 'de')], default='en', max_length=2),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(max_length=63),
        ),
    ]
