# Generated by Django 4.0.2 on 2022-06-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyinfo',
            options={'verbose_name_plural': 'Company Infos'},
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='address_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='address_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='city_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='city_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='name_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
