# Generated by Django 4.0.2 on 2022-06-20 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_info', '0002_alter_companyinfo_options_companyinfo_address_de_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyinfo',
            name='coordinates',
        ),
    ]
