# Generated by Django 4.0.2 on 2022-06-22 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_info', '0004_companyinfo_latitude_companyinfo_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='address_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='city_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
